apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
spec:
  releaseName: minio
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "11.5.1"
  interval: 30s
  install:
    remediation:
      retries: 3
  values:
    service:
      type: LoadBalancer
    auth:
      rootUser: "admin"
      rootPassword: "Hello2000@5"
